# This is the Bun configuration file
# It defines settings for your Bun project.

# Default configuration settings
[default]
# Preload scripts to run before the main application starts
preload = ["./scripts/preload.ts"]

# Set the log level for the application
# Options: "debug" for verbose logging, "warn" for warnings only, "error" for error messages only
logLevel = "debug" # Change this as needed

# Configuration for installing dependencies
[default.install]
# Automatically install dependencies when they are missing
auto = "auto" # Options: "auto" to auto-install, "none" to disable auto-install

# Run a dry run of the install process without actually installing
dryRun = false # Set to true to test the installation without making changes

# Environment-specific configuration (for example, for production)
[production]
logLevel = "error" # Set to "error" for production to reduce verbosity
# You can add more production-specific settings here

# Another environment, for example, staging
[staging]
logLevel = "warn" # Set to "warn" for staging environments
# You can add more staging-specific settings here
[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true